services:
  usuarios-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: usuarios-db
    environment:
      SA_PASSWORD: "usuarios123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - usuarios_data:/var/opt/mssql
    networks:
      - usuarios-net

  usuarios-api:
    build:
      context: ./Usuarios
      dockerfile: Dockerfile
    container_name: usuarios-api
    depends_on:
      - usuarios-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=usuarios-db;Database=UsuariosDb;User Id=sa;Password=usuarios123!;TrustServerCertificate=True;Encrypt=True;
    ports:
      - "5000:8080"
    volumes:
      - ./Usuarios:/app
    networks:
      - usuarios-net

  autenticacion-api:
    build:
      context: ./Autenticacion
      dockerfile: Dockerfile
    container_name: autenticacion-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:8080"
    volumes:
      - ./Autenticacion:/app
    networks:
      - usuarios-net
 
  pedidos-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pedidos-db
    environment:
      SA_PASSWORD: "pedidos123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - pedidos_data:/var/opt/mssql
    networks:
      - usuarios-net
 
  pedidos-api:
    build:
      context: ./Pedidos
      dockerfile: Dockerfile
    container_name: pedidos-api
    depends_on:
      - pedidos-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=pedidos-db;Database=PedidosDb;User Id=sa;Password=pedidos123!;TrustServerCertificate=True;Encrypt=True;
    ports:
      - "5004:8080"
    volumes:
      - ./Pedidos:/app
    networks:
      - usuarios-net

volumes:
  usuarios_data:
  pedidos_data:

networks:
  usuarios-net:
