services:
  usuarios-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: usuarios-db
    environment:
      SA_PASSWORD: "usuarios123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - usuarios_data:/var/opt/mssql
    networks:
      - usuarios-net

  usuarios-api:
    build:
      context: ./Usuarios
      dockerfile: Dockerfile
    container_name: usuarios-api
    depends_on:
      - usuarios-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=usuarios-db;Database=UsuariosDb;User Id=sa;Password=usuarios123!;TrustServerCertificate=True;Encrypt=True;
    ports:
      - "5000:8080"
    volumes:
      - ./Usuarios:/app
    command: sh -c "dotnet restore && dotnet watch run --no-launch-profile"
    networks:
      - usuarios-net

  autenticacion-api:
    build:
      context: ./Autenticacion
      dockerfile: Dockerfile
    container_name: autenticacion-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5001:8080"
    volumes:
      - ./Autenticacion:/app
    command: sh -c "dotnet restore && dotnet watch run --no-launch-profile"
    networks:
      - usuarios-net

  quickshop-mvc:
    build:
      context: ./Quickshop.MVC
      dockerfile: Dockerfile
    container_name: quickshop-mvc
    depends_on:
      - usuarios-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5002:8080"
    volumes:
      - ./Quickshop.MVC:/app
    command: sh -c "dotnet restore && dotnet watch run --no-launch-profile"
    networks:
      - usuarios-net
    
  productos-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: productos-db
    environment:
      SA_PASSWORD: "productos123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - productos_data:/var/opt/mssql
    networks:
      - usuarios-net

  productos-api:
    build:
      context: ./Productos
      dockerfile: Dockerfile
    container_name: productos-api
    depends_on:
      - productos-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=productos-db;Database=ProductosDb;User Id=sa;Password=productos123!;TrustServerCertificate=True;Encrypt=True;
    ports:
      - "5003:8080"
    volumes:
      - ./Productos:/app
    networks:
      - usuarios-net  

volumes:
  usuarios_data:
  productos_data:

networks:
  usuarios-net:
